### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by AlltosSoul** [Latokike/lato-origins#11]
Server crashes when i try to run it with lato origins (my mods are fabric api, origins and of course lato origins)

Logs:

[17:51:55] [main/INFO]: Loading for game Minecraft 1.16.5
[17:51:56] [main/INFO]: [FabricLoader] Loading 64 mods: fabric-renderer-api-v1@0.4.2+2868a2287d, fallflyinglib@1.1.0, fabric-keybindings-v0@0.2.1+ca58154a7d, cardinal-components-block@2.8.2, fabricloader@0.11.2, fabric-structure-api-v1@1.1.4+ca58154a7d, fabric-containers-v0@0.1.11+9354966b7d, fabric-dimensions-v1@2.0.6+61336ba97d, fabric-object-builder-api-v1@1.9.5+c88702897d, pehkui@2.1.0+21w18a, java@8, latoorigins@0.7.0, fabric-game-rule-api-v1@1.0.6+ca58154a7d, fabric-api-base@0.3.0+c88702897d, fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d, cardinal-components-item@2.8.2, fabric-textures-v0@1.0.6+ca58154a7d, fabric-rendering-fluids-v1@0.1.13+ca58154a7d, cardinal-components-level@2.8.2, reach-entity-attributes@1.1.1, fabric-blockrenderlayer-v1@1.1.5+ca58154a7d, fabric-lifecycle-events-v1@1.2.1+ca58154a7d, cardinal-components-chunk@2.8.2, fabric-renderer-registries-v1@2.3.0+2868a2287d, cardinal-components-util@2.8.2, fabric-loot-tables-v1@1.0.2+ca58154a7d, cardinal-components-scoreboard@2.8.2, fabric@0.34.1+1.16, fabric-particles-v1@0.2.4+ca58154a7d, fabric-networking-v0@0.3.2+ca58154a7d, fabric-api-lookup-api-v1@1.0.0+dc716ea17d, minecraft@1.16.5, fabric-screen-handler-api-v1@1.1.5+9354966b7d, fabric-networking-blockentity-v0@0.2.8+ca58154a7d, fabric-command-api-v1@1.1.1+351679a77d, cloth-basic-math@0.5.1, fabric-screen-api-v1@1.0.0+c045166c7d, fabric-tool-attribute-api-v1@1.2.7+8183d3957d, fabric-renderer-indigo@0.4.4+ca58154a7d, fabric-item-api-v1@1.2.1+ca58154a7d, fabric-crash-report-info-v1@0.1.3+ca58154a7d, fabric-events-interaction-v0@0.4.2+ca58154a7d, cardinal-components@2.8.2, fabric-entity-events-v1@1.1.0+c88702897d, origins@0.7.1, fabric-rendering-v0@1.1.2+ca58154a7d, fabric-key-binding-api-v1@1.0.4+9354966b7d, fabric-rendering-v1@1.6.0+2868a2287d, cloth-config2@4.11.14, fabric-resource-loader-v0@0.4.6+2868a2287d, fabric-content-registries-v0@0.2.1+ca58154a7d, cardinal-components-world@2.8.2, fabric-tag-extensions-v0@1.1.1+ca58154a7d, fabric-biome-api-v1@3.1.1+ca58154a7d, cardinal-components-entity@2.8.2, fabric-commands-v0@0.2.2+ca58154a7d, fabric-registry-sync-v0@0.7.4+ca58154a7d, cardinal-components-base@2.8.2, fabric-mining-levels-v0@0.1.3+ca58154a7d, fabric-networking-api-v1@1.0.2+d6244c6d7d, fabric-events-lifecycle-v0@0.2.1+ca58154a7d, fabric-item-groups-v0@0.2.7+2868a2287d, fabric-models-v0@0.3.0+bc7a746f7d, fabric-object-builders-v0@0.7.2+ca58154a7d
[17:51:56] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/home/servers/s9619/server_files/server.jar Service=Knot/Fabric Env=SERVER
[17:51:58] [main/FATAL]: Mixin prepare failed preparing PlayerEntityRendererMixin in latoorigins.mixins.json: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Cannot load class latokike.latoorigins.mixin.PlayerEntityRendererMixin in environment type SERVER
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Cannot load class latokike.latoorigins.mixin.PlayerEntityRendererMixin in environment type SERVER
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:855) ~[server.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:715) ~[server.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:648) ~[server.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:514) [server.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:439) [server.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:415) [server.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285) [server.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) [server.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [server.jar:?]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [server.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) [server.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) [server.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) [?:1.8.0_272]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224) [server.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [server.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [server.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_272]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_272]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_272]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_272]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62) [server.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106) [server.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50) [server.jar:?]
Caused by: java.lang.RuntimeException: Cannot load class latokike.latoorigins.mixin.PlayerEntityRendererMixin in environment type SERVER
	at net.fabricmc.loader.transformer.FabricTransformer.transform(FabricTransformer.java:75) ~[server.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:185) ~[server.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.getClassByteArray(Knot.java:214) ~[server.jar:?]
	at net.fabricmc.loader.launch.knot.MixinServiceKnot.getClassBytes(MixinServiceKnot.java:47) ~[server.jar:?]
	at net.fabricmc.loader.launch.knot.MixinServiceKnot.getClassNode(MixinServiceKnot.java:63) ~[server.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.loadMixinClass(MixinInfo.java:1295) ~[server.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:848) ~[server.jar:?]
	... 22 more

**Comment by latokike** [comment]
Did you install Pehkui?

**Comment by latokike** [comment]
I've found the issue, I'll try to fix it now.

**Comment by latokike** [comment]
It should be fixed now
